# Generated by Django 2.1 on 2019-03-12 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtivoDetalhe',
            fields=[
                ('cod_ativo', models.AutoField(primary_key=True, serialize=False)),
                ('desc_ativo', models.CharField(max_length=250)),
                ('sigla_ativo', models.CharField(max_length=250, unique=True)),
                ('data_inserido', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ativo_detalhe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoAtivo',
            fields=[
                ('cod_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('desc_grupo', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'grupo_ativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoAtivo',
            fields=[
                ('cod_preco', models.BigAutoField(primary_key=True, serialize=False)),
                ('preco', models.FloatField()),
                ('data', models.DateTimeField()),
            ],
            options={
                'db_table': 'price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField()),
                ('preco_entrada', models.FloatField()),
                ('taxa_entrada', models.FloatField()),
                ('preco_atual', models.FloatField()),
                ('taxa_atual', models.FloatField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.AtivoDetalhe')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('data_criacao', models.DateField()),
                ('ativo', models.ManyToManyField(through='portfolios.Aplicacao', to='portfolios.AtivoDetalhe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio'),
        ),
    ]
