# Generated by Django 2.1 on 2019-03-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20190313_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='preco_atual',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='taxa_atual',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='taxa_entrada',
            field=models.FloatField(blank=True),
        ),
    ]
