# Generated by Django 2.1 on 2019-03-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20190314_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='preco_atual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='taxa_atual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='taxa_entrada',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
