# Generated by Django 2.1 on 2019-03-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_auto_20190314_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacao',
            name='quantidade_aplicada',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='rendimento_preco',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='valor_aplicado',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
