# Generated by Django 2.1 on 2019-03-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20190318_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacao',
            name='quantidade_aplicada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aplicacao',
            name='rendimento_preco',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
