# Generated by Django 2.1 on 2019-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20190318_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aplicacao',
            old_name='rendimento_preco',
            new_name='rentabilidade_absoluta',
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='rentabilidade_relativa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
