# Generated by Django 2.1 on 2019-06-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_auto_20190323_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precoativo',
            options={'get_latest_by': '-data', 'managed': False},
        ),
    ]
