# Generated by Django 2.1 on 2019-06-20 18:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_auto_20190609_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proventos',
            fields=[
                ('cod_provento', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_provento', models.FloatField()),
                ('data_com', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('data_inclusao', models.DateTimeField()),
                ('tipo_provento', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'proventos',
                'managed': False,
            },
        ),
        migrations.AlterModelManagers(
            name='aplicacao',
            managers=[
                ('customObjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
