# Generated by Django 2.1 on 2019-06-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_auto_20190620_1559'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aplicacao',
            managers=[
            ],
        ),
    ]
