# Generated by Django 2.1 on 2019-06-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_auto_20190620_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacao',
            name='quantidade_aplicada',
        ),
    ]
