# Generated by Django 2.1 on 2019-07-12 00:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0011_remove_aplicacao_quantidade_aplicada'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='portfolio',
            managers=[
                ('customObjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
