# Generated by Django 2.1 on 2019-07-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_auto_20190711_2155'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='portfolio',
            managers=[
            ],
        ),
    ]
