# Generated by Django 2.1 on 2019-08-11 16:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolios', '0013_auto_20190711_2201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('nome', 'user')},
        ),
    ]
