# Generated by Django 2.1 on 2019-07-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_user',
            field=models.BooleanField(default=False),
        ),
    ]
